// Override KEYBOARD_SIDE if -s flag is used
#if defined SIDE_LEFT
#undef KEYBOARD_SIDE
#define KEYBOARD_SIDE LEFT

#elif defined SIDE_RIGHT
#undef KEYBOARD_SIDE
#define KEYBOARD_SIDE RIGHT
#endif

#if defined SPLIT_KEYBOARD && KEYBOARD_SIDE == RIGHT
#if !defined KEYMAP_CONFIG
#define CONFIG_MUTABLE const
#else
#define CONFIG_MUTABLE
#endif
#define SPLIT_MUTABLE const

#undef ADC_PINS
#define ADC_PINS ADC_PINS_R
#ifdef MUX_PINS
#undef MUX_PINS
#define MUX_PINS MUX_PINS_R
#endif
#undef MUX_CHANNELS
#define MUX_CHANNELS MUX_CHANNELS_R
#ifndef MUX_PINS_RIGHT_CONTINUOUS
#undef MUX_PINS_CONTINUOUS
#else
#undef MUX_PIN_OFFSET
#define MUX_PIN_OFFSET MUX_PIN_RIGHT_OFFSET
#undef CONTINUOUS_MUX_PORT
#define CONTINUOUS_MUX_PORT CONTINUOUS_MUX_PORT_RIGHT
#endif

#ifdef POWER_PINS
#undef POWER_PINS
#define POWER_PINS POWER_PINS_R
#endif
#ifdef MATRIX_POWER_PIN_R
#undef MATRIX_POWER_PIN
#define MATRIX_POWER_PIN MATRIX_POWER_PIN_R
#endif

#undef SWITCH_NUM
#define SWITCH_NUM SWITCH_NUM_R
#undef MUX_TO_NUM
#define MUX_TO_NUM MUX_TO_NUM_R
#undef NUM_TO_MATRIX
#define NUM_TO_MATRIX NUM_TO_MATRIX_R
#undef MATRIX_TO_NUM
#define MATRIX_TO_NUM MATRIX_TO_NUM_R
#undef NUM_TO_MUX
#define NUM_TO_MUX NUM_TO_MUX_R

#if AM_INIT_KEY_NUM_R > 0
#undef AM_INIT_KEY_NUM
#define AM_INIT_KEY_NUM AM_INIT_KEY_NUM_R
#undef AM_INIT_KEYS
#define AM_INIT_KEYS AM_INIT_KEYS_R
#undef AM_INIT_FUNCTIONS
#define AM_INIT_FUNCTIONS AM_INIT_FUNCTIONS_R
#endif

#ifndef KEYMAP_CONFIG
#undef TRIGGER_HEIGHT
#define TRIGGER_HEIGHT TRIGGER_HEIGHT_R
#undef RELEASE_HEIGHT
#define RELEASE_HEIGHT RELEASE_HEIGHT_R
#undef RT_PRESS_DISTANCE
#define RT_PRESS_DISTANCE RT_PRESS_DISTANCE_R
#undef RT_RELEASE_DISTANCE
#define RT_RELEASE_DISTANCE RT_RELEASE_DISTANCE_R
#undef KEY_MODES
#define KEY_MODES KEY_MODES_R
#endif

#ifdef AM_TOP_VALUES_R
#undef AM_TOP_VALUES
#define AM_TOP_VALUES AM_TOP_VALUES_R
#endif
#ifdef AM_BOTTOM_VALUES_R
#undef AM_BOTTOM_VALUES
#define AM_BOTTOM_VALUES AM_BOTTOM_VALUES_R
#endif

#ifdef DEBUG_MUX_POSITION_R
#undef DEBUG_MUX_POSITION
#define DEBUG_MUX_POSITION DEBUG_MUX_POSITION_R
#endif

//TODO: Remove one of the following when I've decided
#ifdef PRIORITY_INDICES
#undef PRIORITY_INDICES
#define PRIORITY_INDICES PRIORITY_INDICES_R
#undef PRIORITY_INDEX_NUM
#define PRIORITY_INDEX_NUM PRIORITY_INDEX_NUM_R
#endif

#ifdef PRIORITY_MUXES
#undef PRIORITY_MUXES
#define PRIORITY_MUXES PRIORITY_MUXES_R
#undef PRIORITY_MUX_NUM
#define PRIORITY_MUX_NUM PRIORITY_MUX_NUM_R
#endif

#ifdef RC_INIT_KEYS_R
#undef RC_INIT_KEYS
#define RC_INIT_KEYS RC_INIT_KEYS_R
#undef RC_INIT_FUNCTIONS
#define RC_INIT_FUNCTIONS_R
#undef RC_INIT_KEY_NUM
#undef RC_INIT_KEY_NUM RC_INIT_KEY_NUM_R
#endif

#endif
